version: '3.8'

services:
  backend:
    build:
      context: ./
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./src/tasklist-frontend
    container_name: frontend
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
